// Barrel for the Drizzle schema. Auth tables (user/session/account/verification/
// two_factor) and the operational + PHI tables are added in later steps; the
// auth tables are generated by better-auth's CLI so their shape matches the
// adapter exactly.
export * from "./reference";
