CREATE TABLE "assessments" (
	"id" text PRIMARY KEY NOT NULL,
	"patient_name" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"dob" text NOT NULL,
	"age" integer NOT NULL,
	"gender" text NOT NULL,
	"health_number" text NOT NULL,
	"consent_given" boolean NOT NULL,
	"consulted_in_365_days" text NOT NULL,
	"ailment_id" text NOT NULL,
	"ailment_name" text NOT NULL,
	"symptoms" jsonb NOT NULL,
	"additional_notes" text,
	"status" text NOT NULL,
	"triage_level" text NOT NULL,
	"severity" text NOT NULL,
	"ai_suggestion" text,
	"recommended_actions" jsonb,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"requires_referral" boolean,
	"referral_reasons" jsonb,
	"demographics" jsonb,
	"pharmacy_id" text
);
